contentColumnType: string
fieldGroup: ec01a46c-7aae-4b10-95ce-6ae6648b9745 # Plugin
handle: categories
instructions: ''
name: Categories
searchable: true
settings:
  branchLimit: ''
  limit: null
  localizeRelations: ''
  selectionLabel: ''
  source: 'group:112552be-dfb0-4cca-a725-b0c4ac73705a'
  sources: '*'
  targetSiteId: null
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
