handle: staff
name: Staff
permissions:
  - accesssitewhensystemisoff
  - accesscpwhensystemisoff
  - accesscp
  - registerusers
  - assignuserpermissions
  - 'assignusergroup:d17f6c64-5872-4457-8784-797b8c3e7ec8'
  - 'assignusergroup:b64bf83a-40fd-48a4-ba39-455b7900f976'
  - assignusergroups
  - editusers
  - deleteusers
  - 'editsite:8928c23a-7002-467d-af97-333694b8dad8'
  - 'editsite:dfc27822-23dd-49e2-ac3a-66a436674cf0'
  - 'editsite:2a835d29-b3e4-4ef5-bf62-ad7285b4a4dd'
  - 'createentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593'
  - 'publishentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593'
  - 'deleteentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593'
  - 'publishpeerentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593'
  - 'deletepeerentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593'
  - 'editpeerentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593'
  - 'publishpeerentrydrafts:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593'
  - 'deletepeerentrydrafts:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593'
  - 'editpeerentrydrafts:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593'
  - 'editentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593'
  - 'saveassetinvolume:238dc7f2-e863-4b8f-96fa-805a3324dc5d'
  - 'createfoldersinvolume:238dc7f2-e863-4b8f-96fa-805a3324dc5d'
  - 'viewvolume:238dc7f2-e863-4b8f-96fa-805a3324dc5d'
  - 'saveassetinvolume:fc4f52d6-458d-44cb-a2fd-f0042d715d64'
  - 'createfoldersinvolume:fc4f52d6-458d-44cb-a2fd-f0042d715d64'
  - 'viewvolume:fc4f52d6-458d-44cb-a2fd-f0042d715d64'
  - 'saveassetinvolume:495fa280-74b9-49af-8737-986532450386'
  - 'createfoldersinvolume:495fa280-74b9-49af-8737-986532450386'
  - 'viewvolume:495fa280-74b9-49af-8737-986532450386'
  - 'utility:system-report'
  - 'utility:php-info'
  - 'utility:asset-indexes'
  - 'utility:clear-caches'
  - 'utility:deprecation-errors'
  - 'utility:db-backup'
  - 'utility:migrations'
  - 'utility:unavailable-plugins'
  - 'craftnet:manageplugins'
  - 'viewpeerfilesinvolume:238dc7f2-e863-4b8f-96fa-805a3324dc5d'
  - 'editpeerfilesinvolume:238dc7f2-e863-4b8f-96fa-805a3324dc5d'
  - 'viewpeerfilesinvolume:fc4f52d6-458d-44cb-a2fd-f0042d715d64'
  - 'editpeerfilesinvolume:fc4f52d6-458d-44cb-a2fd-f0042d715d64'
  - 'viewpeerfilesinvolume:495fa280-74b9-49af-8737-986532450386'
  - 'editpeerfilesinvolume:495fa280-74b9-49af-8737-986532450386'
